openapi: 3.2.0
info:
  title: Customer Classification Assets(.*) API
  description: API for triggering and retrieving classifications for products
  version: 1.0.0
servers:
- url: https://api.smartersorting.com
tags:
- name: Assets
paths:
  /assets(.*):
    get:
      summary: /assets proxy
      description: Proxy assets endpoints to new zudoku portal
      operationId: proxy-assets
      tags:
      - Assets
components:
  securitySchemes:
    api_key:
      type: http
      scheme: bearer
